FROM docker.elastic.co/logstash/logstash:6.3.2
LABEL maintainer="Roberto Rodriguez @Cyb3rWard0g"
LABEL description="Dockerfile Log4j2shell base"

COPY --chown=logstash:logstash config /usr/share/logstash/config